language: python
python: 3.6
sudo: false
env:
    - TOX_ENV=py36
    - TOX_ENV=flake8
    - TOX_ENV=docs
    global:
        - secure: access_token=XXXXX
install:
    - pip3 install coverage nose mock python-coveralls tox
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls
notifications:
    irc: "irc.freenode.org#rpappalax"
